# Generated by Django 6.0.4 on 2026-05-02 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('coat_name', models.CharField(max_length=100)),
                ('genetics', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('personality', models.CharField(choices=[('CALM', 'Calm'), ('AGG', 'Aggressive'), ('NER', 'Nervous'), ('FRI', 'Friendly'), ('STU', 'Stubborn')], default='CALM', max_length=15)),
                ('is_purebred', models.BooleanField(default=True)),
                ('conceived_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Still Owned'), ('SOLD', 'Sold'), ('VOIDED', 'Voided')], default='ACTIVE', max_length=10)),
                ('max_stat', models.BooleanField(default=False)),
                ('trained', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horses', to='RoseLineApp.breed')),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_offspring', to='RoseLineApp.horse')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horses', to=settings.AUTH_USER_MODEL)),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sire_offspring', to='RoseLineApp.horse')),
            ],
        ),
    ]
