# Generated by Django 6.0.4 on 2026-05-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseLineApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
