# Generated by Django 6.0.4 on 2026-05-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseLineApp', '0002_breed_slug_alter_breed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
