# Generated by Django 6.0.4 on 2026-05-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoseLineApp', '0003_horse_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='slug',
        ),
    ]
