# Generated by Django 6.0.4 on 2026-05-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoseLineApp', '0004_remove_breed_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='gender',
            field=models.CharField(choices=[('M', 'Stallion'), ('F', 'Mare')], max_length=1),
        ),
        migrations.AlterField(
            model_name='horse',
            name='personality',
            field=models.CharField(choices=[('ALOOF', 'Aloof'), ('BRONCO', 'Bronco'), ('CAR', 'Carefree'), ('CLINGY', 'Clingy'), ('DAN', 'Dangerous'), ('DIS', 'Distrustful'), ('EXT', 'Extrovert'), ('FEA', 'Fearful'), ('FRESH', 'Fresh'), ('HOT', 'Hotblooded'), ('JUMPY', 'Jumpy'), ('KICK', 'Kickhappy'), ('LAZY', 'Lazy'), ('MINI', 'Minimalist'), ('MUD', 'Mudmagnet'), ('SEN', 'Sensitive'), ('SER', 'Serene'), ('SPI', 'Spirited'), ('RAN', 'Ranchhand'), ('SHOW', 'Showhorse'), ('TRA', 'Tracker'), ('GUA', 'Guardian'), ('FERAL', 'Feral'), ('POCKET', 'Inyourpocket'), ('TRAIL', 'Trailboss')], default='MINI', max_length=15),
        ),
    ]
